# LITERAL CONSTANTS
AFTER = "after"
DATA = "data"
DOMAIN = "domain"
EDGES = "edges"
EDGE_FOLLOW = "edge_follow"
EDGE_FOLLOWED_BY = "edge_followed_by"
END_CURSOR = "end_cursor"
ERROR = "ERROR"
FETCH_MUTUAL = "fetch_mutual"
FIRST = "first"
FIRST_POSITION = 0
FULL_NAME = "full_name"
HAS_NEXT_PAGE = "has_next_page"
ID = "id"
IS_PRIVATE = "is_private"
INCLUDE_REEL = "include_reel"
NAME = "name"
NODE = "node"
PAGE_INFO = "page_info"
PASSWORD = "password"
PK = "pk"
USER = "user"
USER_AGENT = "user-agent"
USERNAME = "username"
USERS = "users"
VALUE = "value"

# NON-LITERAL CONSTANTS
COMMAND_USER_AGENT_SELENIUM = "return navigator.userAgent;"
CSS_SUBMIT = ".\\_abak:nth-child(3)"
SAFE_CHARS_ENCODER = "!~*'()"
MAIN_MESSAGE = "Enter main"
STARTING_MESSAGE = "Starting analysis: "
TOTAL_MESSAGE = "Total: "
URL_INSTAGRAM = "https://www.instagram.com"
URL_INSTAGRAM_LOGOUT = "https://www.instagram.com/accounts/logout/"
URL_QUERY_FOLLOWERS = "https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6415203be841dd25a&variables="
URL_QUERY_FOLLOWINGS = "https://www.instagram.com/graphql/query/?query_hash=d04b0a864b4b54837c0d870b0e77e076&variables="
URL_SEARCH_INSTAGRAM = "https://www.instagram.com/web/search/topsearch/?query="